# Generated by Django 4.2.2 on 2023-11-29 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('employee_id', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('face_image', models.ImageField(blank=True, null=True, upload_to='lab_staff')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_visit', models.DateField()),
                ('doctors_name', models.CharField(max_length=100)),
                ('prescription_img', models.FileField(upload_to='medical_history/prescription')),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('face_image', models.ImageField(upload_to='pharmacist')),
            ],
        ),
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('face_image', models.ImageField(upload_to='receptionist')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=255, null=True)),
                ('LDAP_ID', models.CharField(max_length=15, unique=True)),
                ('LDAP_PASS', models.CharField(max_length=20)),
                ('Face_Image', models.ImageField(blank=True, null=True, upload_to='doctors')),
                ('Phone', models.CharField(blank=True, max_length=255, null=True)),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.TextField(blank=True, null=True)),
                ('City', models.CharField(blank=True, max_length=255, null=True)),
                ('Country', models.CharField(blank=True, max_length=255, null=True)),
                ('Pincode', models.IntegerField(blank=True, null=True)),
                ('Branch', models.CharField(blank=True, choices=[('Computer Science and Engineering', 'Computer Science and Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Aerospace Engineering', 'Aerospace Engineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Metallurgical Engineering and Materials Science', 'Metallurgical Engineering and Materials Science'), ('Materials Engineering', 'Materials Engineering'), ('Energy Science and Engineering', 'Energy Science and Engineering'), ('Environmental Science and Engineering', 'Environmental Science and Engineering'), ('Systems and Control Engineering', 'Systems and Control Engineering'), ('Mechanical Engineering with M.Tech. in Thermal Systems Design', 'Mechanical Engineering with M.Tech. in Thermal Systems Design'), ('Mechanical Engineering with M.Tech. in Design', 'Mechanical Engineering with M.Tech. in Design'), ('Mechanical Engineering with M.Tech. in Manufacturing', 'Mechanical Engineering with M.Tech. in Manufacturing'), ('Mechanical Engineering with M.Tech. in Computer Integrated Manufacturing', 'Mechanical Engineering with M.Tech. in Computer Integrated Manufacturing'), ('Mechanical Engineering with M.Tech. in Computational and Applied Mechanics', 'Mechanical Engineering with M.Tech. in Computational and Applied Mechanics'), ('Chemical Engineering with M.Tech. in Process Engineering', 'Chemical Engineering with M.Tech. in Process Engineering'), ('Chemical Engineering with M.Tech. in Environmental Engineering and Management', 'Chemical Engineering with M.Tech. in Environmental Engineering and Management'), ('Electrical Engineering with M.Tech. in Microelectronics', 'Electrical Engineering with M.Tech. in Microelectronics'), ('Electrical Engineering with M.Tech. in Communication Engineering', 'Electrical Engineering with M.Tech. in Communication Engineering'), ('Electrical Engineering with M.Tech. in Control and Computing', 'Electrical Engineering with M.Tech. in Control and Computing'), ('Electrical Engineering with M.Tech. in Power Electronics and Power Systems', 'Electrical Engineering with M.Tech. in Power Electronics and Power Systems'), ('Electrical Engineering with M.Tech. in Electronics and Communication Engineering', 'Electrical Engineering with M.Tech. in Electronics and Communication Engineering'), ('Electrical Engineering with M.Tech. in Power Systems and Power Electronics', 'Electrical Engineering with M.Tech. in Power Systems and Power Electronics'), ('Electrical Engineering with M.Tech. in Microelectronics', 'Electrical Engineering with M.Tech. in Microelectronics'), ('Mechanical Engineering with M.Tech. in Thermal and Fluids Engineering', 'Mechanical Engineering with M.Tech. in Thermal and Fluids Engineering'), ('Mechanical Engineering with M.Tech. in Design', 'Mechanical Engineering with M.Tech. in Design'), ('Mechanical Engineering with M.Tech. in Manufacturing', 'Mechanical Engineering with M.Tech. in Manufacturing'), ('Mechanical Engineering with M.Tech. in Computer Integrated Manufacturing', 'Mechanical Engineering with M.Tech. in Computer Integrated Manufacturing'), ('Mechanical Engineering with M.Tech. in Computational and Applied Mechanics', 'Mechanical Engineering with M.Tech. in Computational and Applied Mechanics'), ('Civil Engineering with M.Tech. in Transportation Systems Engineering', 'Civil Engineering with M.Tech. in Transportation Systems Engineering'), ('Civil Engineering with M.Tech. in Geotechnical Engineering', 'Civil Engineering with M.Tech. in Geotechnical Engineering'), ('Civil Engineering with M.Tech. in Structural Engineering', 'Civil Engineering with M.Tech. in Structural Engineering'), ('Civil Engineering with M.Tech. in Ocean Engineering', 'Civil Engineering with M.Tech. in Ocean Engineering'), ('Civil Engineering with M.Tech. in Water Resources Engineering', 'Civil Engineering with M.Tech. in Water Resources Engineering'), ('Civil Engineering with M.Tech. in Environmental Engineering and Management', 'Civil Engineering with M.Tech. in Environmental Engineering and Management'), ('Aerospace Engineering with M.Tech. in Aerospace Engineering', 'Aerospace Engineering with M.Tech. in Aerospace Engineering'), ('Aerospace Engineering with M.Tech. in Aerospace Structures', 'Aerospace Engineering with M.Tech. in Aerospace Structures'), ('Aerospace Engineering with M.Tech. in Aerodynamics and Flight Mechanics', 'Aerospace Engineering with M.Tech. in Aerodynamics and Flight Mechanics'), ('Aerospace Engineering with M.Tech. in Propulsion', 'Aerospace Engineering with M.Tech. in Propulsion'), ('Aerospace Engineering with M.Tech. in Systems and Control', 'Aerospace Engineering with M.Tech. in Systems and Control'), ('Aerospace Engineering with M.Tech. in Aerospace Manufacturing', 'Aerospace Engineering with M.Tech. in Aerospace Manufacturing'), ('Aerospace Engineering with M.Tech. in Aerospace Propulsion', 'Aerospace Engineering with M.Tech. in Aerospace Propulsion'), ('Aerospace Engineering with M.Tech. in Aerospace Structures', 'Aerospace Engineering with M.Tech. in Aerospace Structures'), ('Aerospace Engineering with M.Tech. in Systems and Control', 'Aerospace Engineering with M.Tech. in Systems and Control'), ('Materials Science and Engineering with M.Tech. in Ceramics and Composites', 'Materials Science and Engineering with M.Tech. in Ceramics and Composites'), ('Materials Science and Engineering with M.Tech. in Materials Manufacturing', 'Materials Science and Engineering with M.Tech. in Materials Manufacturing'), ('Materials Science and Engineering with M.Tech. in Materials Science', 'Materials Science and Engineering with M.Tech. in Materials Science'), ('Materials Science and Engineering with M.Tech. in Nuclear Materials', 'Materials Science and Engineering with M.Tech. in Nuclear Materials'), ('Materials Science and Engineering with M.Tech. in Metallurgical and Materials Science', 'Materials Science and Engineering with M.Tech. in Metallurgical and Materials Science'), ('Materials Science and Engineering with M.Tech. in Materials Science and Engineering', 'Materials Science and Engineering with M.Tech. in Materials Science and Engineering')], max_length=500, null=True)),
                ('year_of_study', models.CharField(blank=True, choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year'), ('5', 'Fifth Year'), ('6', 'Sixth Year')], max_length=255, null=True)),
                ('Bld_Grp', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('Age', models.PositiveIntegerField()),
                ('Weight_kg', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacist', models.CharField(max_length=100)),
                ('date_received', models.DateField()),
                ('medical_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medicalhistory')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pharmacy_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pharmacydetails')),
            ],
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student'),
        ),
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=100)),
                ('report_pdf', models.FileField(upload_to='medical_history/lab_reports')),
                ('medical_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medicalhistory')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='doctors')),
                ('department', models.CharField(blank=True, max_length=100)),
                ('doctor_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=15)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.doctor')),
            ],
        ),
    ]
