# Generated by Django 4.2.2 on 2023-11-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=255)),
                ('booking_date', models.DateField()),
                ('appointment_date', models.DateField()),
                ('doctor_department', models.ImageField(upload_to='pharmacist')),
            ],
        ),
    ]
