# Generated by Django 4.2.2 on 2023-09-12 14:34

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_apimodel_medical_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medical_history',
            old_name='name',
            new_name='doctors_name',
        ),
        migrations.RemoveField(
            model_name='medical_history',
            name='description',
        ),
        migrations.AddField(
            model_name='medical_history',
            name='date',
            field=models.DateField(default=api.models.default_date),
        ),
        migrations.AddField(
            model_name='medical_history',
            name='presc_img',
            field=models.FileField(default='default_image.jpg', upload_to='med_his_presc'),
        ),
    ]
