# Generated by Django 4.2.2 on 2023-09-12 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_name_medical_history_doctors_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medical_history',
            name='presc_img',
        ),
    ]
