# Generated by Django 4.2.2 on 2023-09-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_presc_img_medicalhistory_prescription_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('employee_id', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('face_image', models.ImageField(blank=True, null=True, upload_to='lab_staff')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='LDAP_ID',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
