# Generated by Django 4.2.2 on 2023-09-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_labstaff_doctor_department_alter_student_ldap_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('face_image', models.ImageField(upload_to='pharmacist')),
            ],
        ),
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('face_image', models.ImageField(upload_to='receptionist')),
            ],
        ),
    ]
