# Generated by Django 4.2.2 on 2023-11-28 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0011_remove_doctor_password_doctor_doctor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
