# Generated by Django 4.2.2 on 2023-11-28 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_doctor_doctor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='doctor_user',
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
